# Generated by Django 3.2.16 on 2023-01-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_witchs_cauldron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='postspell',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='spell_categories', to='the_witchs_cauldron.Categories'),
        ),
    ]
