# Generated by Django 3.2.16 on 2023-02-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_witchs_cauldron', '0002_auto_20230126_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
