# Generated by Django 3.2.16 on 2023-02-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_witchs_cauldron', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Coven curious', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='practice_of_interest',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='the_witchs_cauldron.categories'),
        ),
        migrations.AddField(
            model_name='profile',
            name='titles',
            field=models.TextField(default='Apprentice', max_length=100, unique=True),
        ),
    ]
