# Generated by Django 3.2.16 on 2023-02-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_witchs_cauldron', '0005_auto_20230219_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Coven curious', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='titles',
            field=models.TextField(default='Apprentice', max_length=100),
        ),
    ]
