# Generated by Django 3.2.16 on 2023-02-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_witchs_cauldron', '0006_auto_20230219_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postspell',
            name='status',
        ),
        migrations.AddField(
            model_name='postspell',
            name='items_needed',
            field=models.TextField(blank=True),
        ),
    ]
