# Generated by Django 3.2.16 on 2023-02-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_witchs_cauldron', '0007_auto_20230220_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
